### ISSUE TITLE
Vertical schedule

### ISSUE THREAD

**Issue by PeterPan73** [linmasahiro/jquery.schedule.plus#2]
Hello, congratulations on the good work!
My question is whether it is possible for the program to be vertical - the rooms to be on top and the hours on the left?
Thanks.

**Comment by linmasahiro** [comment]
> Hello, congratulations on the good work!
> My question is whether it is possible for the program to be vertical - the rooms to be on top and the hours on the left?
> Thanks.

hello,
sorry, no support vertical mode schedule now. :(

**Comment by PeterPan73** [comment]
@linmasahiro can you try to help me? How hard is?
Thanks.

**Comment by linmasahiro** [comment]
> @linmasahiro can you try to help me? How hard is?
> Thanks.

thank you for request.
not hard but has many support vertical mode  scheduler on github.
maybe you can try it. :)

**Comment by PeterPan73** [comment]
I really like **your development** and I have already implemented it in my project.
I will be happy if you help me.
Thank you very much.

**Comment by linmasahiro** [comment]
> I really like **your development** and I have already implemented it in my project.
> I will be happy if you help me.
> Thank you very much.

Thank you for like it. but i am busy with new project now.
So i have not time to add new function.  Bad News, Sorry :(
